' AUTO-GENERATED BY B4X++ v0.5.1
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.5.1
' Source: /mnt/data/b4xpp_v051_work/B4XPP-v0.5.0-extension-source-consolidated-release/examples/banano-skeleton/src-b4xpp/Demo.bx
' MainModule: Main



Sub Process_Globals
    Private BANano As BANano 'ignore
End Sub

Sub AppStart (Form1 As Form, Args() As String)
    BANano.Initialize("BANano", "B4XPPBananoSkeletonHello", 1)
    BANano.Header.Title = "B4X++ BANanoSkeleton"
    BANano.JAVASCRIPT_NAME = "app.js"
    BANano.TranspilerOptions.MergeAllCSSFiles = True
    BANano.TranspilerOptions.MergeAllJavascriptFiles = True
    BANano.TranspilerOptions.RemoveDeadCode = False
    BANano.TranspilerOptions.ShowWarningDeadCode = True

    ' BANanoSkeleton theme / assets
    SKTools.WriteTheme

    ' BANano transpiles the B4J project into Objects/B4XPPBananoSkeletonHello/index.html + app.js.
    BANano.Build(File.DirApp)

    #If Release
    ExitApplication
    #End If
End Sub

Sub BANano_Ready()
    Dim body As BANanoElement
    body.Initialize("#body")
    body.Append($"<div class="container" style="margin-top: 32px;">
<h1>B4X++ + BANanoSkeleton</h1>
<p>This page was generated from a .bx source, compiled as B4J, then transpiled by BANano to HTML/CSS/JS.</p>
<button class="button-primary">Hello BANano</button>
</div>"$)

    ' Native BANano.Await must stay untouched by B4X++ Async/Await transformation.
    Dim indexTextProm As BANanoPromise = BANano.GetFileAsText("./index.html", Null, "UTF-8")
    Dim indexText As String = BANano.Await(indexTextProm)
    Log("Loaded index.html chars: " & indexText.Length)
End Sub

#If CSS
body {
    background: #f6f8fb;
}
#End If
