' AUTO-GENERATED BY B4X++ v0.4.0
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.4.0
' Source: B4X++ closure runtime
' Class: B4XPPClosure

Sub Class_Globals
	Private mCallback As Object
	Private mMethodName As String
	Private mCaptures As List
End Sub

Public Sub Initialize(Callback As Object, MethodName As String, Captures As List)
	mCallback = Callback
	mMethodName = MethodName
	mCaptures.Initialize
	If Captures <> Null Then
		If Captures.IsInitialized Then mCaptures = Captures
	End If
End Sub

Private Sub BuildContext(Args As List) As List
	Dim ctx As List
	ctx.Initialize
	ctx.Add(mCaptures)
	ctx.Add(Args)
	Return ctx
End Sub

Private Sub NewArgs As List
	Dim args As List
	args.Initialize
	Return args
End Sub

Public Sub Run As Object
	Return CallSub2(mCallback, mMethodName, BuildContext(NewArgs))
End Sub

Public Sub Run1(Arg1 As Object) As Object
	Dim args As List = NewArgs
	args.Add(Arg1)
	Return CallSub2(mCallback, mMethodName, BuildContext(args))
End Sub

Public Sub Invoke1(Arg1 As Object) As Object
	Return Run1(Arg1)
End Sub

Public Sub Run2(Arg1 As Object, Arg2 As Object) As Object
	Dim args As List = NewArgs
	args.Add(Arg1)
	args.Add(Arg2)
	Return CallSub2(mCallback, mMethodName, BuildContext(args))
End Sub

Public Sub Invoke2(Arg1 As Object, Arg2 As Object) As Object
	Return Run2(Arg1, Arg2)
End Sub

Public Sub Run3(Arg1 As Object, Arg2 As Object, Arg3 As Object) As Object
	Dim args As List = NewArgs
	args.Add(Arg1)
	args.Add(Arg2)
	args.Add(Arg3)
	Return CallSub2(mCallback, mMethodName, BuildContext(args))
End Sub

Public Sub Invoke3(Arg1 As Object, Arg2 As Object, Arg3 As Object) As Object
	Return Run3(Arg1, Arg2, Arg3)
End Sub

Public Sub Run4(Arg1 As Object, Arg2 As Object, Arg3 As Object, Arg4 As Object) As Object
	Dim args As List = NewArgs
	args.Add(Arg1)
	args.Add(Arg2)
	args.Add(Arg3)
	args.Add(Arg4)
	Return CallSub2(mCallback, mMethodName, BuildContext(args))
End Sub

Public Sub Invoke4(Arg1 As Object, Arg2 As Object, Arg3 As Object, Arg4 As Object) As Object
	Return Run4(Arg1, Arg2, Arg3, Arg4)
End Sub

Public Sub Run5(Arg1 As Object, Arg2 As Object, Arg3 As Object, Arg4 As Object, Arg5 As Object) As Object
	Dim args As List = NewArgs
	args.Add(Arg1)
	args.Add(Arg2)
	args.Add(Arg3)
	args.Add(Arg4)
	args.Add(Arg5)
	Return CallSub2(mCallback, mMethodName, BuildContext(args))
End Sub

Public Sub Invoke5(Arg1 As Object, Arg2 As Object, Arg3 As Object, Arg4 As Object, Arg5 As Object) As Object
	Return Run5(Arg1, Arg2, Arg3, Arg4, Arg5)
End Sub

' Alias for users who prefer Invoke naming in generated B4X.
Public Sub Invoke As Object
	Return Run
End Sub
