' AUTO-GENERATED BY B4X++ v0.4.0
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.4.0
' Source: src-b4xpp/Demo.bx
' MainModule: Main



' B4X++ include begin: src-b4xpp/services/TaskRunner.bx

' B4X++ include end: src-b4xpp/services/TaskRunner.bx

Sub Process_Globals
End Sub

Sub AppStart (Args() As String)
    Log("=== B4X++ Closure Console Demo ===")
    BasicGreeting
    CapturedAdder
    PassedClosure
End Sub

Private Sub BasicGreeting
    ' B4XPP_LIFTED_CLOSURE say B4XPP_Closure_Main_BasicGreeting_1 

    B4XPP_Closure_Main_BasicGreeting_1("anonymous Sub without capture")
End Sub

Private Sub CapturedAdder
    Dim a As Int
    a = 2

    ' B4XPP_LIFTED_CLOSURE add B4XPP_Closure_Main_CapturedAdder_2 a

    Log("2 + 5 = " & B4XPP_Closure_Main_CapturedAdder_2(a, 5))
    a = 10
    Log("10 + 5 = " & B4XPP_Closure_Main_CapturedAdder_2(a, 5))
End Sub

Private Sub PassedClosure
    Dim runner As TaskRunner
    runner.Initialize

    Dim factor As Int = 3
    ' B4X++ closure value: multiply -> B4XPP_Closure_Main_PassedClosure_3; captures: factor
    Dim B4XPP_multiply_captures As List
    B4XPP_multiply_captures.Initialize
    B4XPP_multiply_captures.Add(factor)
    Dim multiply As B4XPPClosure
    multiply.Initialize(Me, "B4XPP_Closure_Main_PassedClosure_3", B4XPP_multiply_captures)

    runner.Add("triple", multiply)
    runner.RunAll(7)
End Sub


' B4X++ lifted closure body for say.
Private Sub B4XPP_Closure_Main_BasicGreeting_1(msg As String)
        Log("Message: " & msg)
End Sub

' B4X++ lifted closure body for add.
Private Sub B4XPP_Closure_Main_CapturedAdder_2(a As Int, i As Int) As Int
        Return a + i
End Sub

' B4X++ runtime closure body for multiply.
Public Sub B4XPP_Closure_Main_PassedClosure_3(B4XPP_ctx As List) As Object
	Dim B4XPP_caps As List = B4XPP_ctx.Get(0)
	Dim B4XPP_args As List = B4XPP_ctx.Get(1)
	Dim factor As Int = B4XPP_caps.Get(0)
	Dim value As Int = B4XPP_args.Get(0)
        Return value * factor
End Sub
