' AUTO-GENERATED BY B4X++ v0.3.2
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.3.2
' Source: src-b4xpp/Demo.bx
' StaticCode: ArenaMath


Sub Process_Globals
End Sub

Public Sub Clamp(Value As Int, MinValue As Int, MaxValue As Int) As Int
    If Value < MinValue Then Return MinValue
    If Value > MaxValue Then Return MaxValue
    Return Value
End Sub

Public Sub AbsI(Value As Int) As Int
    If Value < 0 Then Return -Value
    Return Value
End Sub

Public Sub Distance(X1 As Int, Y1 As Int, X2 As Int, Y2 As Int) As Int
    Return AbsI(X1 - X2) + AbsI(Y1 - Y2)
End Sub

Public Sub Sign(Value As Int) As Int
    If Value < 0 Then Return -1
    If Value > 0 Then Return 1
    Return 0
End Sub

Public Sub DirectionLabel(DX As Int, DY As Int) As String
    If DX = 0 And DY = 0 Then Return "wait"
    If AbsI(DX) > AbsI(DY) Then
        If DX > 0 Then Return "east"
        Return "west"
    End If
    If DY > 0 Then Return "south"
    Return "north"
End Sub
