' AUTO-GENERATED BY B4X++ v0.3.2
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.3.2
' Source: B4X++ runtime
' CodeModule: B4XPP_Runtime

Sub Process_Globals
	Private LastResult As Object
End Sub

' Advanced dynamic dispatch. B4X++ generated classes expose B4XPP_Dispatch(MethodName, Args As List).
' The real method arguments are packed in Args, so B4X++ targets support any number of parameters.
' The CallSub fallback is only for external / non-B4X++ objects and is limited by B4X itself.
' Args0 / ArgsN helpers avoid generating Array As Object expressions in user modules.
Public Sub Dispatch(Target As Object, MethodName As String, Args As List) As Object
	LastResult = Null
	If Target = Null Then
		Log("B4X++ dispatch target is Null: " & MethodName)
		Return Null
	End If
	If Args = Null Then Args = Args0
	If SubExists(Target, "B4XPP_Dispatch") Then
		CallSub3(Target, "B4XPP_Dispatch", MethodName, Args)
		Return LastResult
	End If
	Return DispatchExternal(Target, MethodName, Args)
End Sub

' Fallback for objects that were not generated by B4X++.
' B4X only exposes CallSub / CallSub2 / CallSub3, so this path supports 0..2 user arguments.
' For unlimited arguments, use B4X++ generated classes or write a small B4X++ adapter wrapper.
Private Sub DispatchExternal(Target As Object, MethodName As String, Args As List) As Object
	Select Args.Size
		Case 0
			Return Call0(Target, MethodName)
		Case 1
			Return Call1(Target, MethodName, Args.Get(0))
		Case 2
			Return Call2(Target, MethodName, Args.Get(0), Args.Get(1))
		Case Else
			Log("B4X++ external dispatch needs a B4X++ adapter for more than 2 parameters: " & MethodName)
			Return Null
	End Select
End Sub

Public Sub SetResult(Value As Object)
	LastResult = Value
End Sub

Public Sub Args0 As List
	Dim L As List
	L.Initialize
	Return L
End Sub

Public Sub Args1(Arg1 As Object) As List
	Dim L As List
	L.Initialize
	L.Add(Arg1)
	Return L
End Sub

Public Sub Args2(Arg1 As Object, Arg2 As Object) As List
	Dim L As List
	L.Initialize
	L.Add(Arg1)
	L.Add(Arg2)
	Return L
End Sub

Public Sub Args3(Arg1 As Object, Arg2 As Object, Arg3 As Object) As List
	Dim L As List
	L.Initialize
	L.Add(Arg1)
	L.Add(Arg2)
	L.Add(Arg3)
	Return L
End Sub

Public Sub Call0(Target As Object, MethodName As String) As Object
    Return CallSub(Target, MethodName)
End Sub

Public Sub Call1(Target As Object, MethodName As String, Arg1 As Object) As Object
    Return CallSub2(Target, MethodName, Arg1)
End Sub

Public Sub Call2(Target As Object, MethodName As String, Arg1 As Object, Arg2 As Object) As Object
    Return CallSub3(Target, MethodName, Arg1, Arg2)
End Sub
