' AUTO-GENERATED BY B4X++ v0.3.2
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.3.2
' Source: src-b4xpp/Demo.bx
' Class: GameWorld

' B4X++ class modifiers: final.

' B4X++ generated / flattened field(s).
Sub Class_Globals
	Private mWidth As Int = 0
	Private mHeight As Int = 0
	Private mTurn As Int = 0
	Private mHero As Hero
    Private mActors As List
    Private mCollectibles As List
End Sub




' B4X++ constructor: generated as Initialize
Public Sub Initialize(Width As Int, Height As Int)
    mWidth = Width
    mHeight = Height
    mTurn = 0
    mActors.Initialize
    mCollectibles.Initialize
End Sub

Public Sub StartDemo
    Dim heroPlayer As Hero
    heroPlayer.Initialize("hero-1", "Ada", 1, 1)
    mHero = heroPlayer
    AddActor(heroPlayer)

    Dim slimeOne As Slime
    slimeOne.Initialize("slime-1", 4, 1)
    AddActor(slimeOne)

    Dim goblinOne As Goblin
    goblinOne.Initialize("goblin-1", 6, 4)
    goblinOne.Name = "Sneaky Goblin"
    AddActor(goblinOne)

    Dim bossOne As Boss
    bossOne.Initialize("boss-1", "Captain Bug", 7, 5)
    AddActor(bossOne)

    Dim potionOne As HealthPotion
    potionOne.Initialize("potion-1", 2, 1, 8)
    AddCollectible(potionOne)

    Dim boostOne As DamageBoost
    boostOne.Initialize("boost-1", 3, 1, 2)
    AddCollectible(boostOne)

    Log(Render)

    For i = 1 To 12
        RunTurn
        Log(Render)
        If mHero.IsAlive = False Then
            Log("Game over: the hero was defeated.")
            Exit
        End If
        If CountLivingEnemies = 0 Then
            Log("Victory: all enemies defeated.")
            Exit
        End If
    Next
End Sub

Public Sub AddActor(ActorObject As Object)
    mActors.Add(ActorObject)
End Sub

Public Sub AddCollectible(ItemObject As Object)
    mCollectibles.Add(ItemObject)
End Sub

Public Sub MoveActor(ActorObject As Object, DX As Int, DY As Int)
    ' B4X++ Poly<IActor>: generated As Object with dynamic dispatch.
    Dim actorAgent As Object
    actorAgent = ActorObject
    Dim currentX As Int = B4XPP_Runtime.Dispatch(actorAgent, "GetPosX", B4XPP_Runtime.Args0)
    Dim currentY As Int = B4XPP_Runtime.Dispatch(actorAgent, "GetPosY", B4XPP_Runtime.Args0)
    B4XPP_Runtime.Dispatch(actorAgent, "SetPosX", B4XPP_Runtime.Args1(ArenaMath.Clamp(currentX + DX, 0, mWidth - 1)))
    B4XPP_Runtime.Dispatch(actorAgent, "SetPosY", B4XPP_Runtime.Args1(ArenaMath.Clamp(currentY + DY, 0, mHeight - 1)))
    CollectItemsForHero
End Sub

Public Sub RunTurn
    mTurn = mTurn + 1
    Log("-- turn " & mTurn & " --")
    CollectItemsForHero

    For i = 0 To mActors.Size - 1
        ' B4X++ Poly<IActor>: generated As Object with dynamic dispatch.
        Dim actorAgent As Object
        actorAgent = mActors.Get(i)
        Dim actorIsAlive As Boolean = B4XPP_Runtime.Dispatch(actorAgent, "IsAlive", B4XPP_Runtime.Args0)
        If actorIsAlive Then B4XPP_Runtime.Dispatch(actorAgent, "TakeTurn", B4XPP_Runtime.Args1(Me))
    Next
End Sub

Public Sub FindNearestEnemy(StartX As Int, StartY As Int) As Object
    Dim bestEnemy As Object = Null
    Dim bestDistance As Int = 999999

    For i = 0 To mActors.Size - 1
        ' B4X++ Poly<IActor>: generated As Object with dynamic dispatch.
        Dim actorAgent As Object
        actorAgent = mActors.Get(i)
        Dim actorIsAlive As Boolean = B4XPP_Runtime.Dispatch(actorAgent, "IsAlive", B4XPP_Runtime.Args0)
        Dim actorTeam As String = B4XPP_Runtime.Dispatch(actorAgent, "Team", B4XPP_Runtime.Args0)
        Dim actorIsEnemy As Boolean
        If actorTeam = "enemy" Then
            actorIsEnemy = True
        Else
            actorIsEnemy = False
        End If
        If actorIsAlive And actorIsEnemy Then
            Dim actorX As Int = B4XPP_Runtime.Dispatch(actorAgent, "GetPosX", B4XPP_Runtime.Args0)
            Dim actorY As Int = B4XPP_Runtime.Dispatch(actorAgent, "GetPosY", B4XPP_Runtime.Args0)
            Dim distanceToCandidate As Int = ArenaMath.Distance(StartX, StartY, actorX, actorY)
            If distanceToCandidate < bestDistance Then
                bestEnemy = mActors.Get(i)
                bestDistance = distanceToCandidate
            End If
        End If
    Next

    Return bestEnemy
End Sub

Public Sub CountLivingEnemies As Int
    Dim count As Int = 0
    For i = 0 To mActors.Size - 1
        ' B4X++ Poly<IActor>: generated As Object with dynamic dispatch.
        Dim actorAgent As Object
        actorAgent = mActors.Get(i)
        Dim actorIsAlive As Boolean = B4XPP_Runtime.Dispatch(actorAgent, "IsAlive", B4XPP_Runtime.Args0)
        Dim actorTeam As String = B4XPP_Runtime.Dispatch(actorAgent, "Team", B4XPP_Runtime.Args0)
        Dim actorIsEnemy As Boolean
        If actorTeam = "enemy" Then
            actorIsEnemy = True
        Else
            actorIsEnemy = False
        End If
        If actorIsAlive And actorIsEnemy Then count = count + 1
    Next
    Return count
End Sub

Private Sub CollectItemsForHero
    If mHero = Null Then Return
    For i = 0 To mCollectibles.Size - 1
        ' B4X++ Poly<ICollectible>: generated As Object with dynamic dispatch.
        Dim itemAgent As Object
        itemAgent = mCollectibles.Get(i)
        Dim itemWasPicked As Boolean = B4XPP_Runtime.Dispatch(itemAgent, "IsPicked", B4XPP_Runtime.Args0)
        If itemWasPicked = False Then
            Dim heroX As Int = mHero.getX
            Dim heroY As Int = mHero.getY
            Dim sameTile As Boolean = B4XPP_Runtime.Dispatch(itemAgent, "SameTile", B4XPP_Runtime.Args2(heroX, heroY))
            If sameTile Then
                Dim line As String = B4XPP_Runtime.Dispatch(itemAgent, "ApplyTo", B4XPP_Runtime.Args1(mHero))
                If line.Length > 0 Then Log(line)
            End If
        End If
    Next
End Sub

Public Sub Render As String
    Dim sb As StringBuilder
    sb.Initialize
    sb.Append(CRLF).Append("Arena ").Append(mWidth).Append("x").Append(mHeight).Append(" turn=").Append(mTurn).Append(CRLF)
    sb.Append("Actors:").Append(CRLF)

    For i = 0 To mActors.Size - 1
        ' B4X++ Poly<IRenderable>: generated As Object with dynamic dispatch.
        Dim renderableActor As Object
        renderableActor = mActors.Get(i)
        sb.Append("  - ").Append(B4XPP_Runtime.Dispatch(renderableActor, "Render", B4XPP_Runtime.Args0)).Append(CRLF)
    Next

    sb.Append("Items:").Append(CRLF)
    For i = 0 To mCollectibles.Size - 1
        ' B4X++ Poly<IRenderable>: generated As Object with dynamic dispatch.
        Dim renderableItem As Object
        renderableItem = mCollectibles.Get(i)
        sb.Append("  - ").Append(B4XPP_Runtime.Dispatch(renderableItem, "Render", B4XPP_Runtime.Args0)).Append(CRLF)
    Next

    Return sb.ToString
End Sub


' B4X++ property: public Width As Int (readonly) default=0
Public Sub getWidth As Int
	Return mWidth
End Sub


' B4X++ property: public Height As Int (readonly) default=0
Public Sub getHeight As Int
	Return mHeight
End Sub


' B4X++ property: public Turn As Int (readonly) default=0
Public Sub getTurn As Int
	Return mTurn
End Sub


' B4X++ property: public Hero As Hero (readonly)
Public Sub getHero As Hero
	Return mHero
End Sub


' B4X++ dynamic dispatch entry point used by Poly<T>.
' Result values are returned through B4XPP_Runtime.SetResult to keep generated class modules broadly compatible.
Public Sub B4XPP_Dispatch(MethodName As String, Args As List)
	Select MethodName.ToLowerCase
		Case "startdemo"
			StartDemo
			B4XPP_Runtime.SetResult(Null)
			Return
		Case "addactor"
			AddActor(Args.Get(0))
			B4XPP_Runtime.SetResult(Null)
			Return
		Case "addcollectible"
			AddCollectible(Args.Get(0))
			B4XPP_Runtime.SetResult(Null)
			Return
		Case "moveactor"
			MoveActor(Args.Get(0), Args.Get(1), Args.Get(2))
			B4XPP_Runtime.SetResult(Null)
			Return
		Case "runturn"
			RunTurn
			B4XPP_Runtime.SetResult(Null)
			Return
		Case "findnearestenemy"
			B4XPP_Runtime.SetResult(FindNearestEnemy(Args.Get(0), Args.Get(1)))
			Return
		Case "countlivingenemies"
			B4XPP_Runtime.SetResult(CountLivingEnemies)
			Return
		Case "render"
			B4XPP_Runtime.SetResult(Render)
			Return
	End Select
	Log("B4X++ dynamic method not found: " & MethodName)
	B4XPP_Runtime.SetResult(Null)
End Sub
