' AUTO-GENERATED BY B4X++ v0.3.2
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.3.2
' Source: src-b4xpp/Demo.bx
' Class: GameObject

' B4X++ class modifiers: abstract.
' B4X++ Implements: IRenderable.

' B4X++ generated / flattened field(s).
Sub Class_Globals
	Private mId As String = ""
	Private mName As String = "Object"
	Private mX As Int = 0
	Private mY As Int = 0
End Sub



' B4X++ constructor: generated as Initialize
Public Sub Initialize(Id As String, Name As String)
    mId = Id
    mName = Name
    mX = 0
    mY = 0
End Sub

' B4X++ constructor: generated as Initialize2
Public Sub Initialize2(Id As String, Name As String, X As Int, Y As Int)
    mId = Id
    mName = Name
    mX = X
    mY = Y
End Sub

' B4X++ modifiers=virtual
Public Sub Render As String
    Return mName & "@" & FormatPosition
End Sub

Public Sub SameTile(TileX As Int, TileY As Int) As Boolean
    Return mX = TileX And mY = TileY
End Sub

' B4X++ visibility=protected
Private Sub FormatPosition As String
    Return "(" & mX & "," & mY & ")"
End Sub


' B4X++ property: public Id As String (readonly) default=""
Public Sub getId As String
	Return mId
End Sub


' B4X++ property: public Name As String default="Object"
Public Sub getName As String
	Return mName
End Sub

Public Sub setName(B4XPP_Name As String)
	mName = B4XPP_Name
End Sub

' B4X++ property: public X As Int default=0
Public Sub getX As Int
	Return mX
End Sub

Public Sub setX(B4XPP_X As Int)
	mX = B4XPP_X
End Sub

' B4X++ property: public Y As Int default=0
Public Sub getY As Int
	Return mY
End Sub

Public Sub setY(B4XPP_Y As Int)
	mY = B4XPP_Y
End Sub

' B4X++ dynamic dispatch entry point used by Poly<T>.
' Result values are returned through B4XPP_Runtime.SetResult to keep generated class modules broadly compatible.
Public Sub B4XPP_Dispatch(MethodName As String, Args As List)
	Select MethodName.ToLowerCase
		Case "render"
			B4XPP_Runtime.SetResult(Render)
			Return
		Case "sametile"
			B4XPP_Runtime.SetResult(SameTile(Args.Get(0), Args.Get(1)))
			Return
		Case "formatposition"
			B4XPP_Runtime.SetResult(FormatPosition)
			Return
	End Select
	Log("B4X++ dynamic method not found: " & MethodName)
	B4XPP_Runtime.SetResult(Null)
End Sub
