' AUTO-GENERATED BY B4X++ v0.3.2
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.3.2
' Source: src-b4xpp/Demo.bx
' Class: Goblin

' B4X++ Extends: Enemy. Output is flattened into this .bas file.
' B4X++ flattened ancestors: GameObject -> Actor -> Enemy.
' B4X++ class modifiers: final.

' B4X++ generated / flattened field(s).
Sub Class_Globals
	Private B4XPP_Private_GameObject_mId As String = ""
	Private B4XPP_Private_GameObject_mName As String = "Object"
	Private B4XPP_Private_GameObject_mX As Int = 0
	Private B4XPP_Private_GameObject_mY As Int = 0
	Private B4XPP_Private_Actor_mHealth As Int = 10
	Private B4XPP_Private_Actor_mMaxHealth As Int = 10
	Private B4XPP_Private_Actor_mAttackPower As Int = 1
	Private B4XPP_Private_Actor_mSpeed As Int = 1
	Private B4XPP_Private_Enemy_mAggroRange As Int = 3
End Sub



' B4X++ constructor: generated as Initialize
Public Sub B4XPP_Super_GameObject_Initialize(Id As String, Name As String)
    B4XPP_Private_GameObject_mId = Id
    B4XPP_Private_GameObject_mName = Name
    B4XPP_Private_GameObject_mX = 0
    B4XPP_Private_GameObject_mY = 0
End Sub

' B4X++ constructor: generated as Initialize2
Public Sub B4XPP_Super_GameObject_Initialize2(Id As String, Name As String, X As Int, Y As Int)
    B4XPP_Private_GameObject_mId = Id
    B4XPP_Private_GameObject_mName = Name
    B4XPP_Private_GameObject_mX = X
    B4XPP_Private_GameObject_mY = Y
End Sub

' B4X++ modifiers=virtual
Public Sub B4XPP_Super_GameObject_Render As String
    Return B4XPP_Private_GameObject_mName & "@" & FormatPosition
End Sub

Public Sub SameTile(TileX As Int, TileY As Int) As Boolean
    Return B4XPP_Private_GameObject_mX = TileX And B4XPP_Private_GameObject_mY = TileY
End Sub

' B4X++ visibility=protected
Private Sub FormatPosition As String
    Return "(" & B4XPP_Private_GameObject_mX & "," & B4XPP_Private_GameObject_mY & ")"
End Sub


' B4X++ property: public Id As String (readonly) default=""
Public Sub getId As String
	Return B4XPP_Private_GameObject_mId
End Sub


' B4X++ property: public Name As String default="Object"
Public Sub getName As String
	Return B4XPP_Private_GameObject_mName
End Sub

Public Sub setName(B4XPP_Name As String)
	B4XPP_Private_GameObject_mName = B4XPP_Name
End Sub

' B4X++ property: public X As Int default=0
Public Sub getX As Int
	Return B4XPP_Private_GameObject_mX
End Sub

Public Sub setX(B4XPP_X As Int)
	B4XPP_Private_GameObject_mX = B4XPP_X
End Sub

' B4X++ property: public Y As Int default=0
Public Sub getY As Int
	Return B4XPP_Private_GameObject_mY
End Sub

Public Sub setY(B4XPP_Y As Int)
	B4XPP_Private_GameObject_mY = B4XPP_Y
End Sub



' B4X++ constructor: generated as Initialize
Public Sub B4XPP_Super_Actor_Initialize(Id As String, Name As String, X As Int, Y As Int, MaxHealth As Int, AttackPower As Int)
    B4XPP_Super_GameObject_Initialize2(Id, Name, X, Y)
    setMaxHealth(MaxHealth)
    setHealth(MaxHealth)
    setAttackPower(AttackPower)
    setSpeed(1)
End Sub

Public Sub IsAlive As Boolean
    Return getHealth > 0
End Sub

Public Sub GetPosX As Int
    Return getX
End Sub

Public Sub SetPosX(Value As Int)
    setX(Value)
End Sub

Public Sub GetPosY As Int
    Return getY
End Sub

Public Sub SetPosY(Value As Int)
    setY(Value)
End Sub

' B4X++ modifiers=virtual
Public Sub B4XPP_Super_Actor_Team As String
    Return "neutral"
End Sub

' B4X++ modifiers=virtual
Public Sub B4XPP_Super_Actor_TakeTurn(World As Object)
End Sub

' B4X++ modifiers=virtual
Public Sub ReceiveDamage(Amount As Int, Source As Object) As String
    Dim beforeHealth As Int = getHealth
    setHealth(getHealth - Amount)
    Return getName & " takes " & (beforeHealth - getHealth) & " damage. HP=" & getHealth & "/" & getMaxHealth
End Sub

' B4X++ modifiers=virtual
Public Sub B4XPP_Super_Actor_Attack(Target As Object) As String
    ' B4X++ Poly<IActor>: generated As Object with dynamic dispatch.
    Dim targetActor As Object
    targetActor = Target
    Dim targetAlive As Boolean = B4XPP_Runtime.Dispatch(targetActor, "IsAlive", B4XPP_Runtime.Args0)
    If targetAlive = False Then Return getName & " has no living target."
    Return getName & " attacks. " & B4XPP_Runtime.Dispatch(targetActor, "ReceiveDamage", B4XPP_Runtime.Args2(getAttackPower, Me))
End Sub

' B4X++ visibility=protected
Private Sub MoveToward(Target As Object, World As GameWorld) As String
    ' B4X++ Poly<IActor>: generated As Object with dynamic dispatch.
    Dim targetActor As Object
    targetActor = Target
    Dim targetX As Int = B4XPP_Runtime.Dispatch(targetActor, "GetPosX", B4XPP_Runtime.Args0)
    Dim targetY As Int = B4XPP_Runtime.Dispatch(targetActor, "GetPosY", B4XPP_Runtime.Args0)
    Dim dx As Int = ArenaMath.Sign(targetX - getX)
    Dim dy As Int = ArenaMath.Sign(targetY - getY)
    If ArenaMath.AbsI(targetX - getX) >= ArenaMath.AbsI(targetY - getY) Then
        dy = 0
    Else
        dx = 0
    End If
    World.MoveActor(Me, dx, dy)
    Return getName & " moves " & ArenaMath.DirectionLabel(dx, dy) & " to " & FormatPosition
End Sub

' B4X++ modifiers=override
Public Sub B4XPP_Super_Actor_Render As String
    Return B4XPP_Super_GameObject_Render & " hp=" & getHealth & "/" & getMaxHealth & " atk=" & getAttackPower
End Sub


' B4X++ property: public Health As Int default=10
Public Sub getHealth As Int
	Return B4XPP_Private_Actor_mHealth
End Sub

Public Sub setHealth(B4XPP_Health As Int)
	B4XPP_Private_Actor_mHealth = B4XPP_Health
End Sub

' B4X++ property: public MaxHealth As Int default=10
Public Sub getMaxHealth As Int
	Return B4XPP_Private_Actor_mMaxHealth
End Sub

Public Sub setMaxHealth(B4XPP_MaxHealth As Int)
	B4XPP_Private_Actor_mMaxHealth = B4XPP_MaxHealth
End Sub

' B4X++ property: public AttackPower As Int default=1
Public Sub getAttackPower As Int
	Return B4XPP_Private_Actor_mAttackPower
End Sub

Public Sub setAttackPower(B4XPP_AttackPower As Int)
	B4XPP_Private_Actor_mAttackPower = B4XPP_AttackPower
End Sub

' B4X++ property: public Speed As Int default=1
Public Sub getSpeed As Int
	Return B4XPP_Private_Actor_mSpeed
End Sub

Public Sub setSpeed(B4XPP_Speed As Int)
	B4XPP_Private_Actor_mSpeed = B4XPP_Speed
End Sub



' B4X++ constructor: generated as Initialize
Public Sub B4XPP_Super_Enemy_Initialize(Id As String, Name As String, X As Int, Y As Int, MaxHealth As Int, AttackPower As Int, AggroRange As Int)
    B4XPP_Super_Actor_Initialize(Id, Name, X, Y, MaxHealth, AttackPower)
    setAggroRange(AggroRange)
End Sub

' B4X++ modifiers=override
Public Sub Team As String
    Return "enemy"
End Sub

' B4X++ modifiers=override
Public Sub TakeTurn(World As Object)
    Dim arenaWorld As GameWorld = World
    Dim heroTarget As Object = arenaWorld.Hero
    ' B4X++ Poly<IActor>: generated As Object with dynamic dispatch.
    Dim heroActor As Object
    heroActor = heroTarget
    Dim heroIsAlive As Boolean = B4XPP_Runtime.Dispatch(heroActor, "IsAlive", B4XPP_Runtime.Args0)
    If IsAlive = False Or heroIsAlive = False Then Return

    Dim heroX As Int = B4XPP_Runtime.Dispatch(heroActor, "GetPosX", B4XPP_Runtime.Args0)
    Dim heroY As Int = B4XPP_Runtime.Dispatch(heroActor, "GetPosY", B4XPP_Runtime.Args0)
    Dim distanceToHero As Int = ArenaMath.Distance(getX, getY, heroX, heroY)
    If distanceToHero <= 1 Then
        Log(Attack(heroTarget))
    Else If distanceToHero <= getAggroRange Then
        Log(MoveToward(heroTarget, arenaWorld))
    Else
        Log(WarCry)
    End If
End Sub

' B4X++ visibility=protected; modifiers=virtual
Private Sub B4XPP_Super_Enemy_WarCry As String
    Return getName & " waits in the dark."
End Sub

' B4X++ modifiers=override
Public Sub Render As String
    Return B4XPP_Super_Actor_Render & " aggro=" & getAggroRange
End Sub


' B4X++ property: public AggroRange As Int default=3
Public Sub getAggroRange As Int
	Return B4XPP_Private_Enemy_mAggroRange
End Sub

Public Sub setAggroRange(B4XPP_AggroRange As Int)
	B4XPP_Private_Enemy_mAggroRange = B4XPP_AggroRange
End Sub


' B4X++ constructor: generated as Initialize
Public Sub Initialize(Id As String, X As Int, Y As Int)
    B4XPP_Super_Enemy_Initialize(Id, "Goblin", X, Y, 12, 4, 5)
End Sub


' B4X++ modifiers=override
Public Sub Attack(Target As Object) As String
    Return "[Goblin] " & B4XPP_Super_Actor_Attack(Target)
End Sub

' B4X++ modifiers=override
Public Sub WarCry As String
    Return getName & " sharpens a tiny blade."
End Sub


' B4X++ dynamic dispatch entry point used by Poly<T>.
' Result values are returned through B4XPP_Runtime.SetResult to keep generated class modules broadly compatible.
Public Sub B4XPP_Dispatch(MethodName As String, Args As List)
	Select MethodName.ToLowerCase
		Case "attack"
			B4XPP_Runtime.SetResult(Attack(Args.Get(0)))
			Return
		Case "warcry"
			B4XPP_Runtime.SetResult(WarCry)
			Return
		Case "team"
			B4XPP_Runtime.SetResult(Team)
			Return
		Case "taketurn"
			TakeTurn(Args.Get(0))
			B4XPP_Runtime.SetResult(Null)
			Return
		Case "render"
			B4XPP_Runtime.SetResult(Render)
			Return
		Case "isalive"
			B4XPP_Runtime.SetResult(IsAlive)
			Return
		Case "getposx"
			B4XPP_Runtime.SetResult(GetPosX)
			Return
		Case "setposx"
			SetPosX(Args.Get(0))
			B4XPP_Runtime.SetResult(Null)
			Return
		Case "getposy"
			B4XPP_Runtime.SetResult(GetPosY)
			Return
		Case "setposy"
			SetPosY(Args.Get(0))
			B4XPP_Runtime.SetResult(Null)
			Return
		Case "receivedamage"
			B4XPP_Runtime.SetResult(ReceiveDamage(Args.Get(0), Args.Get(1)))
			Return
		Case "movetoward"
			B4XPP_Runtime.SetResult(MoveToward(Args.Get(0), Args.Get(1)))
			Return
		Case "sametile"
			B4XPP_Runtime.SetResult(SameTile(Args.Get(0), Args.Get(1)))
			Return
		Case "formatposition"
			B4XPP_Runtime.SetResult(FormatPosition)
			Return
	End Select
	Log("B4X++ dynamic method not found: " & MethodName)
	B4XPP_Runtime.SetResult(Null)
End Sub
