' AUTO-GENERATED BY B4X++ v0.3.2
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.3.2
' Source: src-b4xpp/Demo.bx
' Class: HealthPotion

' B4X++ Extends: Item. Output is flattened into this .bas file.
' B4X++ flattened ancestors: GameObject -> Item.
' B4X++ class modifiers: final.

' B4X++ generated / flattened field(s).
Sub Class_Globals
	Private B4XPP_Private_GameObject_mId As String = ""
	Private B4XPP_Private_GameObject_mName As String = "Object"
	Private B4XPP_Private_GameObject_mX As Int = 0
	Private B4XPP_Private_GameObject_mY As Int = 0
	Private B4XPP_Private_Item_mPicked As Boolean = False
	Private mAmount As Int = 10
End Sub



' B4X++ constructor: generated as Initialize
Public Sub B4XPP_Super_GameObject_Initialize(Id As String, Name As String)
    B4XPP_Private_GameObject_mId = Id
    B4XPP_Private_GameObject_mName = Name
    B4XPP_Private_GameObject_mX = 0
    B4XPP_Private_GameObject_mY = 0
End Sub

' B4X++ constructor: generated as Initialize2
Public Sub B4XPP_Super_GameObject_Initialize2(Id As String, Name As String, X As Int, Y As Int)
    B4XPP_Private_GameObject_mId = Id
    B4XPP_Private_GameObject_mName = Name
    B4XPP_Private_GameObject_mX = X
    B4XPP_Private_GameObject_mY = Y
End Sub

' B4X++ modifiers=virtual
Public Sub B4XPP_Super_GameObject_Render As String
    Return B4XPP_Private_GameObject_mName & "@" & FormatPosition
End Sub

Public Sub SameTile(TileX As Int, TileY As Int) As Boolean
    Return B4XPP_Private_GameObject_mX = TileX And B4XPP_Private_GameObject_mY = TileY
End Sub

' B4X++ visibility=protected
Private Sub FormatPosition As String
    Return "(" & B4XPP_Private_GameObject_mX & "," & B4XPP_Private_GameObject_mY & ")"
End Sub


' B4X++ property: public Id As String (readonly) default=""
Public Sub getId As String
	Return B4XPP_Private_GameObject_mId
End Sub


' B4X++ property: public Name As String default="Object"
Public Sub getName As String
	Return B4XPP_Private_GameObject_mName
End Sub

Public Sub setName(B4XPP_Name As String)
	B4XPP_Private_GameObject_mName = B4XPP_Name
End Sub

' B4X++ property: public X As Int default=0
Public Sub getX As Int
	Return B4XPP_Private_GameObject_mX
End Sub

Public Sub setX(B4XPP_X As Int)
	B4XPP_Private_GameObject_mX = B4XPP_X
End Sub

' B4X++ property: public Y As Int default=0
Public Sub getY As Int
	Return B4XPP_Private_GameObject_mY
End Sub

Public Sub setY(B4XPP_Y As Int)
	B4XPP_Private_GameObject_mY = B4XPP_Y
End Sub



' B4X++ constructor: generated as Initialize
Public Sub B4XPP_Super_Item_Initialize(Id As String, Name As String, X As Int, Y As Int)
    B4XPP_Super_GameObject_Initialize2(Id, Name, X, Y)
    setPicked(False)
End Sub

Public Sub IsPicked As Boolean
    Return getPicked
End Sub

' B4X++ modifiers=virtual
Public Sub B4XPP_Super_Item_ApplyTo(Target As Object) As String
    setPicked(True)
    Return getName & " disappears."
End Sub

' B4X++ modifiers=override
Public Sub Render As String
    Return "item:" & B4XPP_Super_GameObject_Render & " picked=" & getPicked
End Sub


' B4X++ property: public Picked As Boolean default=False
Public Sub getPicked As Boolean
	Return B4XPP_Private_Item_mPicked
End Sub

Public Sub setPicked(B4XPP_Picked As Boolean)
	B4XPP_Private_Item_mPicked = B4XPP_Picked
End Sub



' B4X++ constructor: generated as Initialize
Public Sub Initialize(Id As String, X As Int, Y As Int, Amount As Int)
    B4XPP_Super_Item_Initialize(Id, "Health Potion", X, Y)
    setAmount(Amount)
End Sub

' B4X++ modifiers=override
Public Sub ApplyTo(Target As Object) As String
    If getPicked Then Return ""
    Dim heroTarget As Hero = Target
    setPicked(True)
    Return heroTarget.Heal(getAmount)
End Sub


' B4X++ property: public Amount As Int default=10
Public Sub getAmount As Int
	Return mAmount
End Sub

Public Sub setAmount(B4XPP_Amount As Int)
	mAmount = B4XPP_Amount
End Sub

' B4X++ dynamic dispatch entry point used by Poly<T>.
' Result values are returned through B4XPP_Runtime.SetResult to keep generated class modules broadly compatible.
Public Sub B4XPP_Dispatch(MethodName As String, Args As List)
	Select MethodName.ToLowerCase
		Case "applyto"
			B4XPP_Runtime.SetResult(ApplyTo(Args.Get(0)))
			Return
		Case "ispicked"
			B4XPP_Runtime.SetResult(IsPicked)
			Return
		Case "render"
			B4XPP_Runtime.SetResult(Render)
			Return
		Case "sametile"
			B4XPP_Runtime.SetResult(SameTile(Args.Get(0), Args.Get(1)))
			Return
		Case "formatposition"
			B4XPP_Runtime.SetResult(FormatPosition)
			Return
	End Select
	Log("B4X++ dynamic method not found: " & MethodName)
	B4XPP_Runtime.SetResult(Null)
End Sub
