' AUTO-GENERATED BY B4X++ v0.4.0
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.4.0
' Source: examples/oop-dungeon-arena/src-b4xpp/Demo.bx
' Class: Item

' B4X++ Extends: GameObject. Output is flattened into this .bas file.
' B4X++ flattened ancestors: GameObject.
' B4X++ class modifiers: abstract.
' B4X++ Implements: ICollectible.

' B4X++ generated / flattened field(s).
Sub Class_Globals
	Private B4XPP_Private_GameObject_mId As String = ""
	Private B4XPP_Private_GameObject_mName As String = "Object"
	Private B4XPP_Private_GameObject_mX As Int = 0
	Private B4XPP_Private_GameObject_mY As Int = 0
	Private mPicked As Boolean = False
End Sub



' B4X++ constructor: generated as Initialize
Public Sub B4XPP_Super_GameObject_Initialize(aId As String, aName As String)
    B4XPP_Private_GameObject_mId = aId
    B4XPP_Private_GameObject_mName = aName
    B4XPP_Private_GameObject_mX = 0
    B4XPP_Private_GameObject_mY = 0
End Sub

' B4X++ constructor: generated as Initialize2
Public Sub B4XPP_Super_GameObject_Initialize2(aId As String, aName As String, aX As Int, aY As Int)
    B4XPP_Private_GameObject_mId = aId
    B4XPP_Private_GameObject_mName = aName
    B4XPP_Private_GameObject_mX = aX
    B4XPP_Private_GameObject_mY = aY
End Sub

' B4X++ modifiers=virtual
Public Sub B4XPP_Super_GameObject_Render As String
    Return B4XPP_Private_GameObject_mName & "@" & FormatPosition
End Sub

Public Sub SameTile(TileX As Int, TileY As Int) As Boolean
    Return B4XPP_Private_GameObject_mX = TileX And B4XPP_Private_GameObject_mY = TileY
End Sub

' B4X++ visibility=protected
Private Sub FormatPosition As String
    Return "(" & B4XPP_Private_GameObject_mX & "," & B4XPP_Private_GameObject_mY & ")"
End Sub


' B4X++ property: public Id As String (readonly) default=""
Public Sub getId As String
	Return B4XPP_Private_GameObject_mId
End Sub


' B4X++ property: public Name As String default="Object"
Public Sub getName As String
	Return B4XPP_Private_GameObject_mName
End Sub

Public Sub setName(B4XPP_Name As String)
	B4XPP_Private_GameObject_mName = B4XPP_Name
End Sub

' B4X++ property: public X As Int default=0
Public Sub getX As Int
	Return B4XPP_Private_GameObject_mX
End Sub

Public Sub setX(B4XPP_X As Int)
	B4XPP_Private_GameObject_mX = B4XPP_X
End Sub

' B4X++ property: public Y As Int default=0
Public Sub getY As Int
	Return B4XPP_Private_GameObject_mY
End Sub

Public Sub setY(B4XPP_Y As Int)
	B4XPP_Private_GameObject_mY = B4XPP_Y
End Sub



' B4X++ constructor: generated as Initialize
Public Sub Initialize(aId As String, aName As String, aX As Int, aY As Int)
    B4XPP_Super_GameObject_Initialize2(aId, aName, aX, aY)
    setPicked(False)
End Sub

Public Sub IsPicked As Boolean
    Return getPicked
End Sub

' B4X++ modifiers=virtual
Public Sub ApplyTo(Target As Object) As String
    setPicked(True)
    Return getName & " disappears."
End Sub

' B4X++ modifiers=override
Public Sub Render As String
    Return "item:" & B4XPP_Super_GameObject_Render & " picked=" & getPicked
End Sub


' B4X++ property: public Picked As Boolean default=False
Public Sub getPicked As Boolean
	Return mPicked
End Sub

Public Sub setPicked(B4XPP_Picked As Boolean)
	mPicked = B4XPP_Picked
End Sub

' B4X++ dynamic dispatch entry point used by Poly<T>.
' Result values are returned through B4XPP_Runtime.SetResult to keep generated class modules broadly compatible.
Public Sub B4XPP_Dispatch(MethodName As String, Args As List)
	Select MethodName.ToLowerCase
		Case "ispicked"
			B4XPP_Runtime.SetResult(IsPicked)
			Return
		Case "applyto"
			B4XPP_Runtime.SetResult(ApplyTo(Args.Get(0)))
			Return
		Case "render"
			B4XPP_Runtime.SetResult(Render)
			Return
		Case "sametile"
			B4XPP_Runtime.SetResult(SameTile(Args.Get(0), Args.Get(1)))
			Return
		Case "formatposition"
			B4XPP_Runtime.SetResult(FormatPosition)
			Return
	End Select
	Log("B4X++ dynamic method not found: " & MethodName)
	B4XPP_Runtime.SetResult(Null)
End Sub
