' AUTO-GENERATED BY B4X++ v0.3.2
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.3.2
' Source: src-b4xpp/Demo.bx
' MainModule: Main



' B4X++ include begin: src-b4xpp/contracts/IRenderable.bx

' B4X++ include end: src-b4xpp/contracts/IRenderable.bx
' B4X++ include begin: src-b4xpp/contracts/IActor.bx

' B4X++ include end: src-b4xpp/contracts/IActor.bx
' B4X++ include begin: src-b4xpp/contracts/ICollectible.bx

' B4X++ include end: src-b4xpp/contracts/ICollectible.bx
' B4X++ include begin: src-b4xpp/core/ArenaMath.bx

' B4X++ include end: src-b4xpp/core/ArenaMath.bx
' B4X++ include begin: src-b4xpp/core/GameObject.bx

' B4X++ include end: src-b4xpp/core/GameObject.bx
' B4X++ include begin: src-b4xpp/actors/Actor.bx

' B4X++ include end: src-b4xpp/actors/Actor.bx
' B4X++ include begin: src-b4xpp/actors/Hero.bx

' B4X++ include end: src-b4xpp/actors/Hero.bx
' B4X++ include begin: src-b4xpp/actors/Enemy.bx

' B4X++ include end: src-b4xpp/actors/Enemy.bx
' B4X++ include begin: src-b4xpp/actors/Slime.bx

' B4X++ include end: src-b4xpp/actors/Slime.bx
' B4X++ include begin: src-b4xpp/actors/Goblin.bx

' B4X++ include end: src-b4xpp/actors/Goblin.bx
' B4X++ include begin: src-b4xpp/actors/Boss.bx

' B4X++ include end: src-b4xpp/actors/Boss.bx
' B4X++ include begin: src-b4xpp/items/Item.bx

' B4X++ include end: src-b4xpp/items/Item.bx
' B4X++ include begin: src-b4xpp/items/HealthPotion.bx

' B4X++ include end: src-b4xpp/items/HealthPotion.bx
' B4X++ include begin: src-b4xpp/items/DamageBoost.bx

' B4X++ include end: src-b4xpp/items/DamageBoost.bx
' B4X++ include begin: src-b4xpp/services/GameWorld.bx

' B4X++ include end: src-b4xpp/services/GameWorld.bx

Sub Process_Globals
End Sub

Sub AppStart (Args() As String)
    Log("=== B4X++ OOP Dungeon Arena ===")

    Dim world As GameWorld
    world.Initialize(8, 6)
    world.StartDemo
End Sub
