' AUTO-GENERATED BY B4X++ v0.1
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.1
' Source: src-b4xpp/Demo.bx
' Class: Dog

' B4X++ Extends: Animal. Output is flattened into this .bas file.
' B4X++ flattened ancestors: Animal.
' B4X++ class modifiers: final.

' B4X++ generated / flattened field(s).
Sub Class_Globals
	Private mName As String = "Unknown"
End Sub



Public Sub B4XPP_Super_Animal_Initialize(Name As String)
    mName = Name
End Sub

' B4X++ modifiers: virtual
Public Sub B4XPP_Super_Animal_Speak As String
    Return "I am " & mName
End Sub

' B4X++ modifiers: virtual
Public Sub B4XPP_Super_Animal_Move(Distance As Int) As String
    Return mName & " moves " & FormatDistance(Distance)
End Sub

' B4X++ modifiers: protected
Public Sub FormatDistance(Distance As Int) As String
    Return Distance & " m"
End Sub


' B4X++ property: Name As String (readonly) default="Unknown"
Public Sub getName As String
	Return mName
End Sub



Public Sub Initialize(Name As String)
    B4XPP_Super_Animal_Initialize(Name)
End Sub

' B4X++ modifiers: override
Public Sub Speak As String
    Return getName & " says woof"
End Sub

' B4X++ modifiers: override
Public Sub Move(Distance As Int) As String
    Return getName & " runs " & Distance & " m"
End Sub


' B4X++ dynamic dispatch entry point used by Poly<T>.
' Result values are returned through B4XPP_Runtime.SetResult to keep generated class modules broadly compatible.
Public Sub B4XPP_Dispatch(MethodName As String, Args As List)
	Select MethodName.ToLowerCase
		Case "speak"
			B4XPP_Runtime.SetResult(Speak)
			Return
		Case "move"
			B4XPP_Runtime.SetResult(Move(Args.Get(0)))
			Return
		Case "formatdistance"
			B4XPP_Runtime.SetResult(FormatDistance(Args.Get(0)))
			Return
	End Select
	Log("B4X++ dynamic method not found: " & MethodName)
	B4XPP_Runtime.SetResult(Null)
End Sub
