' AUTO-GENERATED BY B4X++ v0.1
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.1
' Source: src-b4xpp/Demo.bx
' MainModule: Main



' B4X++ include begin: src-b4xpp/contracts/IAnimal.bx

' B4X++ include end: src-b4xpp/contracts/IAnimal.bx
' B4X++ include begin: src-b4xpp/models/Animal.bx

' B4X++ include end: src-b4xpp/models/Animal.bx
' B4X++ include begin: src-b4xpp/models/Dog.bx

' B4X++ include end: src-b4xpp/models/Dog.bx
' B4X++ include begin: src-b4xpp/models/Cat.bx

' B4X++ include end: src-b4xpp/models/Cat.bx
' B4X++ include begin: src-b4xpp/models/Bird.bx

' B4X++ include end: src-b4xpp/models/Bird.bx

Sub Process_Globals
End Sub

Sub AppStart (Args() As String)
    Dim dogInstance As Dog
    dogInstance.Initialize("Rex")

    Dim catInstance As Cat
    catInstance.Initialize("Misty")

    Dim birdInstance As Bird
    birdInstance.Initialize("Tweety")

    Log(dogInstance.Speak)
    Log(catInstance.Speak)
    Log(birdInstance.Speak)

    ' Natural polymorphism: Dog / Cat / Bird extend Animal.
    ' B4X++ detects the child assignments and generates Object + dynamic dispatch.
    ' B4X++ implicit polymorphism: animalInstance As Animal generated As Object with dynamic dispatch.
    Dim animalInstance As Object

    animalInstance = dogInstance
    Log(B4XPP_Runtime.Dispatch(animalInstance, "Speak", B4XPP_Runtime.Args0))
    Log(B4XPP_Runtime.Dispatch(animalInstance, "Move", B4XPP_Runtime.Args1(3)))

    animalInstance = catInstance
    Log(B4XPP_Runtime.Dispatch(animalInstance, "Speak", B4XPP_Runtime.Args0))

    animalInstance = birdInstance
    Log(B4XPP_Runtime.Dispatch(animalInstance, "Move", B4XPP_Runtime.Args1(10)))
End Sub
