' AUTO-GENERATED BY B4X++ v0.1
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.1
' Source: src-b4xpp/Demo.bx
' Class: BaseComponent

' B4X++ class modifiers: abstract.
' B4X++ Implements: IRenderable, IIdentifiable.

#DesignerProperty: Key: Title, DisplayName: Title, FieldType: String, DefaultValue: Untitled, Description: Component title
#Event: Click

' B4X++ generated / flattened field(s).
Sub Class_Globals
	Private mId As String
	Private mTitle As String = "Untitled"
	Private mCreatedAt As Long = 0
End Sub




Public Sub Initialize(Id As String, Title As String)
    mId = Id
    mTitle = Title
    mCreatedAt = DateTime.Now
End Sub

' B4X++ modifiers: virtual
Public Sub Identity As String
    Return mId
End Sub

' B4X++ modifiers: abstract
Public Sub ComponentType As String
    Log("B4X++ abstract method called: BaseComponent.ComponentType")
    Return ""
End Sub

' B4X++ modifiers: virtual
Public Sub Render(Theme As String, Scale As Int, Debug As Boolean) As String
    Return BuildRenderLine("base", Theme, Scale, Debug)
End Sub

' B4X++ modifiers: protected
Public Sub BuildRenderLine(Kind As String, Theme As String, Scale As Int, Debug As Boolean) As String
    Return Kind & ":" & mId & " title=" & mTitle & " theme=" & Theme & " scale=" & Scale & " debug=" & Debug
End Sub

' B4X++ modifiers: final
Public Sub Signature As String
    Return mId & "-" & mCreatedAt
End Sub


' B4X++ property: Id As String (readonly)
Public Sub getId As String
	Return mId
End Sub


' B4X++ property: Title As String default="Untitled"
Public Sub getTitle As String
	Return mTitle
End Sub

Public Sub setTitle(Value As String)
	mTitle = Value
End Sub

' B4X++ property: CreatedAt As Long (readonly) default=0
Public Sub getCreatedAt As Long
	Return mCreatedAt
End Sub


' B4X++ dynamic dispatch entry point used by Poly<T>.
' Result values are returned through B4XPP_Runtime.SetResult to keep generated class modules broadly compatible.
Public Sub B4XPP_Dispatch(MethodName As String, Args As List)
	Select MethodName.ToLowerCase
		Case "identity"
			B4XPP_Runtime.SetResult(Identity)
			Return
		Case "componenttype"
			B4XPP_Runtime.SetResult(ComponentType)
			Return
		Case "render"
			B4XPP_Runtime.SetResult(Render(Args.Get(0), Args.Get(1), Args.Get(2)))
			Return
		Case "buildrenderline"
			B4XPP_Runtime.SetResult(BuildRenderLine(Args.Get(0), Args.Get(1), Args.Get(2), Args.Get(3)))
			Return
		Case "signature"
			B4XPP_Runtime.SetResult(Signature)
			Return
	End Select
	Log("B4X++ dynamic method not found: " & MethodName)
	B4XPP_Runtime.SetResult(Null)
End Sub
