' AUTO-GENERATED BY B4X++ v0.1
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.1
' Source: src-b4xpp/Demo.bx
' Class: ComponentRegistry

' B4X++ generated / flattened field(s).
Sub Class_Globals
	Private mLastRendered As String = ""
End Sub



Public Sub Initialize()
End Sub

' B4X++ modifiers: virtual
Public Sub Store(Component As Object) As String
    ' B4X++ Poly<IRenderable>: generated As Object with dynamic dispatch.
    Dim renderable As Object
    renderable = Component
    mLastRendered = B4XPP_Runtime.Dispatch(renderable, "Render", B4XPP_Runtime.Args3("registry", 1, False))
    Return mLastRendered
End Sub


' B4X++ property: LastRendered As String (writeonly) default=""
Public Sub setLastRendered(Value As String)
	mLastRendered = Value
End Sub

' B4X++ dynamic dispatch entry point used by Poly<T>.
' Result values are returned through B4XPP_Runtime.SetResult to keep generated class modules broadly compatible.
Public Sub B4XPP_Dispatch(MethodName As String, Args As List)
	Select MethodName.ToLowerCase
		Case "store"
			B4XPP_Runtime.SetResult(Store(Args.Get(0)))
			Return
	End Select
	Log("B4X++ dynamic method not found: " & MethodName)
	B4XPP_Runtime.SetResult(Null)
End Sub
