' AUTO-GENERATED BY B4X++ v0.1
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.1
' Source: src-b4xpp/Demo.bx
' MainModule: Main



' B4X++ include begin: src-b4xpp/contracts/IRenderable.bx

' B4X++ include end: src-b4xpp/contracts/IRenderable.bx
' B4X++ include begin: src-b4xpp/contracts/IIdentifiable.bx

' B4X++ include end: src-b4xpp/contracts/IIdentifiable.bx
' B4X++ include begin: src-b4xpp/core/BaseComponent.bx

' B4X++ include end: src-b4xpp/core/BaseComponent.bx
' B4X++ include begin: src-b4xpp/components/ButtonComponent.bx

' B4X++ include end: src-b4xpp/components/ButtonComponent.bx
' B4X++ include begin: src-b4xpp/components/LabelComponent.bx

' B4X++ include end: src-b4xpp/components/LabelComponent.bx
' B4X++ include begin: src-b4xpp/services/ComponentRegistry.bx

' B4X++ include end: src-b4xpp/services/ComponentRegistry.bx

Sub Process_Globals
End Sub

Sub AppStart (Args() As String)
    Dim button As ButtonComponent
    button.Initialize("save", "Save")
    button.Enabled = True

    Dim label As LabelComponent
    label.Initialize("title", "Welcome")
    label.Text = "B4X++ language showcase"

    ' B4X++ Poly<IRenderable>: generated As Object with dynamic dispatch.
    Dim renderable As Object
    renderable = button
    Log(B4XPP_Runtime.Dispatch(renderable, "Render", B4XPP_Runtime.Args3("dark", 2, True)))

    renderable = label
    Log(B4XPP_Runtime.Dispatch(renderable, "Render", B4XPP_Runtime.Args3("light", 1, False)))

    Dim registry As ComponentRegistry
    registry.Initialize
    Log(registry.Store(button))
End Sub
