' AUTO-GENERATED BY B4X++ v0.3.5
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.3.5
' Source: src-b4xpp/Demo.bx
' Class: GameEntity

' B4X++ class modifiers: abstract.
' B4X++ Implements: IRenderable.

' B4X++ generated / flattened field(s).
Sub Class_Globals
	Private mX As Float = 0
	Private mY As Float = 0
	Private mWidth As Float = 10
	Private mHeight As Float = 10
	Private mColor As Int = 0
	Private mVisible As Boolean = True
End Sub



' B4X++ constructor: generated as Initialize
Public Sub Initialize(aX As Float, aY As Float, aWidth As Float, aHeight As Float, aColor As Int)
    ' Shared entity setup: B4X++ property assignment calls the generated setters.
    setX(aX)
    setY(aY)
    setWidth(aWidth)
    setHeight(aHeight)
    setColor(aColor)
    setVisible(True)
End Sub

Public Sub Left As Float
    ' Left edge of the entity rectangle.
    Return getX
End Sub

Public Sub Top As Float
    ' Top edge of the entity rectangle.
    Return getY
End Sub

Public Sub Right As Float
    ' Right edge of the entity rectangle.
    Return getX + getWidth
End Sub

Public Sub Bottom As Float
    ' Bottom edge of the entity rectangle.
    Return getY + getHeight
End Sub

Public Sub CenterX As Float
    ' Horizontal center used by the ball and paddle logic.
    Return BreakoutMath.CenterOf(getX, getWidth)
End Sub

Public Sub CenterY As Float
    ' Vertical center used by the ball rendering.
    Return BreakoutMath.CenterOf(getY, getHeight)
End Sub

Public Sub SetPosition(aNewX As Float, aNewY As Float)
    ' Moves the entity without changing its size.
    setX(aNewX)
    setY(aNewY)
End Sub

Public Sub CollidesWithBox(aOtherLeft As Float, aOtherTop As Float, aOtherRight As Float, aOtherBottom As Float) As Boolean
    ' Rectangle collision helper. Safer than Intersects(GameEntity) after B4X++ flattening.
    Return BreakoutMath.Overlaps(Left, Top, Right, Bottom, aOtherLeft, aOtherTop, aOtherRight, aOtherBottom)
End Sub

' B4X++ visibility=protected
Private Sub EntityRect As B4XRect
    ' Reusable rectangle for B4XCanvas drawing.
    Dim entityArea As B4XRect
    entityArea.Initialize(Left, Top, Right, Bottom)
    Return entityArea
End Sub

' B4X++ modifiers=virtual
Public Sub Render(aCvs As B4XCanvas)
    ' Default renderer for rectangular entities.
    If getVisible = False Then Return
    aCvs.DrawRect(EntityRect, getColor, True, 0)
End Sub


' B4X++ property: public X As Float default=0
Public Sub getX As Float
	Return mX
End Sub

Public Sub setX(B4XPP_X As Float)
	mX = B4XPP_X
End Sub

' B4X++ property: public Y As Float default=0
Public Sub getY As Float
	Return mY
End Sub

Public Sub setY(B4XPP_Y As Float)
	mY = B4XPP_Y
End Sub

' B4X++ property: public Width As Float default=10
Public Sub getWidth As Float
	Return mWidth
End Sub

Public Sub setWidth(B4XPP_Width As Float)
	mWidth = B4XPP_Width
End Sub

' B4X++ property: public Height As Float default=10
Public Sub getHeight As Float
	Return mHeight
End Sub

Public Sub setHeight(B4XPP_Height As Float)
	mHeight = B4XPP_Height
End Sub

' B4X++ property: public Color As Int default=0
Public Sub getColor As Int
	Return mColor
End Sub

Public Sub setColor(B4XPP_Color As Int)
	mColor = B4XPP_Color
End Sub

' B4X++ property: public Visible As Boolean default=True
Public Sub getVisible As Boolean
	Return mVisible
End Sub

Public Sub setVisible(B4XPP_Visible As Boolean)
	mVisible = B4XPP_Visible
End Sub
