' AUTO-GENERATED BY B4X++ v0.3.5
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.3.5
' Source: src-b4xpp/Demo.bx
' Class: ScoreBoard

' B4X++ class modifiers: final.

' B4X++ generated / flattened field(s).
Sub Class_Globals
	Private mScore As Int = 0
	Private mLives As Int = 3
	Private mRunning As Boolean = False
	Private mMessage As String = "Move the mouse to control the paddle. Click to launch."
    Private xui As XUI
End Sub




Public Sub Initialize
    ' Resets HUD state for a new game.
    setScore(0)
    setLives(3)
    setRunning(False)
    setMessage("Move the mouse to control the paddle. Click to launch.")
End Sub

Public Sub AddScore(aPoints As Int)
    ' Adds brick score to the total.
    setScore(getScore + aPoints)
End Sub

Public Sub LoseLife As Boolean
    ' Stops the ball and returns True when the game is over.
    setLives(getLives - 1)
    If getLives <= 0 Then
        setRunning(False)
        setMessage("Game over. Click to restart.")
        Return True
    End If
    setRunning(False)
    setMessage("Life lost. Click to relaunch.")
    Return False
End Sub

Public Sub WinGame
    ' Stops the level and shows the victory message.
    setRunning(False)
    setMessage("Victory! All bricks cleared. Click to restart.")
End Sub

Public Sub Render(aCvs As B4XCanvas, aGameWidth As Float)
    ' Draws score, lives and status message.
    aCvs.DrawText("Score: " & getScore, 12dip, 25dip, xui.CreateDefaultBoldFont(16), xui.Color_White, "LEFT")
    aCvs.DrawText("Lives: " & getLives, aGameWidth - 12dip, 25dip, xui.CreateDefaultBoldFont(16), xui.Color_White, "RIGHT")
    If getMessage.Length > 0 Then
        aCvs.DrawText(getMessage, aGameWidth / 2, 455dip, xui.CreateDefaultFont(14), xui.Color_White, "CENTER")
    End If
End Sub


' B4X++ property: public Score As Int default=0
Public Sub getScore As Int
	Return mScore
End Sub

Public Sub setScore(B4XPP_Score As Int)
	mScore = B4XPP_Score
End Sub

' B4X++ property: public Lives As Int default=3
Public Sub getLives As Int
	Return mLives
End Sub

Public Sub setLives(B4XPP_Lives As Int)
	mLives = B4XPP_Lives
End Sub

' B4X++ property: public Running As Boolean default=False
Public Sub getRunning As Boolean
	Return mRunning
End Sub

Public Sub setRunning(B4XPP_Running As Boolean)
	mRunning = B4XPP_Running
End Sub

' B4X++ property: public Message As String default="Move the mouse to control the paddle. Click to launch."
Public Sub getMessage As String
	Return mMessage
End Sub

Public Sub setMessage(B4XPP_Message As String)
	mMessage = B4XPP_Message
End Sub
