' AUTO-GENERATED BY B4X++ v0.4.2
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.4.2
' Source: src-b4xpp/Demo.bx
' MainModule: Main


Sub AppStart (Args() As String)
    Dim result As Result__String
    ' B4X++ auto-init result As Result__String
    result.Initialize
    result.InitializeSuccess("B4X++ generics")

    Dim names As TypedList__String
    ' B4X++ auto-init names As TypedList__String
    names.Initialize
    names.Add(result.Value)
    names.Add("source-generated")

    Dim scores As TypedMap__String__Int
    ' B4X++ auto-init scores As TypedMap__String__Int
    scores.Initialize
    scores.Put("generics", 1)
    scores.Put("b4xpplib", 2)

    Log(names.Get(0))
    Log(scores.Get("b4xpplib"))
End Sub
