' AUTO-GENERATED BY B4X++ v0.4.2
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.4.2
' Source: ../../b4xpp-libs/B4XPP.Core.b4xpplib::TypedList.bx
' Class: TypedList__String

' B4X++ generated / flattened field(s).
Sub Class_Globals
    Private mList As List
End Sub


Public Sub Initialize
    mList.Initialize
End Sub

Public Sub Add(aValue As String)
    mList.Add(aValue)
End Sub

Public Sub Get(Index As Int) As String
    Return mList.Get(Index)
End Sub

Public Sub Set(Index As Int, aValue As String)
    mList.Set(Index, aValue)
End Sub

Public Sub RemoveAt(Index As Int) As String
    Dim RemovedValue As String = mList.Get(Index)
    mList.RemoveAt(Index)
    Return RemovedValue
End Sub

Public Sub Clear
    mList.Clear
End Sub

Public Sub Size As Int
    Return mList.Size
End Sub

Public Sub RawList As List
    Return mList
End Sub
