' AUTO-GENERATED BY B4X++ v0.4.2
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.4.2
' Source: ../../b4xpp-libs/B4XPP.Core.b4xpplib::TypedMap.bx
' Class: TypedMap__String__Int

' B4X++ generated / flattened field(s).
Sub Class_Globals
    Private mMap As Map
End Sub


Public Sub Initialize
    mMap.Initialize
End Sub

Public Sub Put(aKey As String, aValue As Int)
    mMap.Put(aKey, aValue)
End Sub

Public Sub Get(aKey As String) As Int
    Return mMap.Get(aKey)
End Sub

Public Sub GetDefault(aKey As String, aDefaultValue As Int) As Int
    Return mMap.GetDefault(aKey, aDefaultValue)
End Sub

Public Sub ContainsKey(aKey As String) As Boolean
    Return mMap.ContainsKey(aKey)
End Sub

Public Sub Remove(aKey As String) As Int
    Dim RemovedValue As Int = mMap.Get(aKey)
    mMap.Remove(aKey)
    Return RemovedValue
End Sub

Public Sub Clear
    mMap.Clear
End Sub

Public Sub Size As Int
    Return mMap.Size
End Sub

Public Sub RawMap As Map
    Return mMap
End Sub
