' AUTO-GENERATED BY B4X++ v0.3.5
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.3.5
' Source: src-b4xpp/Demo.bx
' StaticCode: BreakoutMath


Sub Process_Globals
End Sub

Public Sub ClampF(Value As Float, MinValue As Float, MaxValue As Float) As Float
    If Value < MinValue Then Return MinValue
    If Value > MaxValue Then Return MaxValue
    Return Value
End Sub

Public Sub AbsF(Value As Float) As Float
    If Value < 0 Then Return -Value
    Return Value
End Sub

Public Sub Overlaps(LeftA As Float, TopA As Float, RightA As Float, BottomA As Float, LeftB As Float, TopB As Float, RightB As Float, BottomB As Float) As Boolean
    If RightA < LeftB Then Return False
    If LeftA > RightB Then Return False
    If BottomA < TopB Then Return False
    If TopA > BottomB Then Return False
    Return True
End Sub

Public Sub CenterOf(LeftValue As Float, SizeValue As Float) As Float
    Return LeftValue + SizeValue / 2
End Sub
