' AUTO-GENERATED BY B4X++ v0.3.5
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.3.5
' Source: src-b4xpp/Demo.bx
' MainModule: Main



' B4X++ include begin: src-b4xpp/contracts/IRenderable.bx

' B4X++ include end: src-b4xpp/contracts/IRenderable.bx
' B4X++ include begin: src-b4xpp/core/BreakoutMath.bx

' B4X++ include end: src-b4xpp/core/BreakoutMath.bx
' B4X++ include begin: src-b4xpp/entities/GameEntity.bx

' B4X++ include end: src-b4xpp/entities/GameEntity.bx
' B4X++ include begin: src-b4xpp/entities/Paddle.bx

' B4X++ include end: src-b4xpp/entities/Paddle.bx
' B4X++ include begin: src-b4xpp/entities/Ball.bx

' B4X++ include end: src-b4xpp/entities/Ball.bx
' B4X++ include begin: src-b4xpp/entities/Brick.bx

' B4X++ include end: src-b4xpp/entities/Brick.bx
' B4X++ include begin: src-b4xpp/services/BrickGrid.bx

' B4X++ include end: src-b4xpp/services/BrickGrid.bx
' B4X++ include begin: src-b4xpp/services/ScoreBoard.bx

' B4X++ include end: src-b4xpp/services/ScoreBoard.bx
' B4X++ include begin: src-b4xpp/services/BreakoutGame.bx

' B4X++ include end: src-b4xpp/services/BreakoutGame.bx

Sub Process_Globals
    Private fx As JFX
    Private MainForm As Form
    Private breakoutApp As BreakoutGame
    Private gameClock As Timer
End Sub

Sub AppStart (Form1 As Form, Args() As String)
    MainForm = Form1
    MainForm.Title = "B4X++ XUI Breakout"
    MainForm.Resizable = False
    MainForm.WindowWidth = 660dip
    MainForm.WindowHeight = 540dip

    Dim rootView As B4XView = MainForm.RootPane

    breakoutApp.Initialize(rootView)
    breakoutApp.StartPlay

    gameClock.Initialize("GameClock", 16)
    gameClock.Enabled = True

    MainForm.Show
End Sub

Sub GameClock_Tick
    breakoutApp.UpdateFrame
End Sub
