' AUTO-GENERATED BY B4X++ v0.3.5
' DO NOT EDIT THIS FILE DIRECTLY
' GeneratorVersion: 0.3.5
' Source: src-b4xpp/Demo.bx
' Class: Paddle

' B4X++ Extends: GameEntity. Output is flattened into this .bas file.
' B4X++ flattened ancestors: GameEntity.
' B4X++ class modifiers: final.

' B4X++ generated / flattened field(s).
Sub Class_Globals
	Private B4XPP_Private_GameEntity_mX As Float = 0
	Private B4XPP_Private_GameEntity_mY As Float = 0
	Private B4XPP_Private_GameEntity_mWidth As Float = 10
	Private B4XPP_Private_GameEntity_mHeight As Float = 10
	Private B4XPP_Private_GameEntity_mColor As Int = 0
	Private B4XPP_Private_GameEntity_mVisible As Boolean = True
	Private mSpeed As Float = 720
End Sub



' B4X++ constructor: generated as Initialize
Public Sub B4XPP_Super_GameEntity_Initialize(aX As Float, aY As Float, aWidth As Float, aHeight As Float, aColor As Int)
    ' Shared entity setup: B4X++ property assignment calls the generated setters.
    setX(aX)
    setY(aY)
    setWidth(aWidth)
    setHeight(aHeight)
    setColor(aColor)
    setVisible(True)
End Sub

Public Sub Left As Float
    ' Left edge of the entity rectangle.
    Return getX
End Sub

Public Sub Top As Float
    ' Top edge of the entity rectangle.
    Return getY
End Sub

Public Sub Right As Float
    ' Right edge of the entity rectangle.
    Return getX + getWidth
End Sub

Public Sub Bottom As Float
    ' Bottom edge of the entity rectangle.
    Return getY + getHeight
End Sub

Public Sub CenterX As Float
    ' Horizontal center used by the ball and paddle logic.
    Return BreakoutMath.CenterOf(getX, getWidth)
End Sub

Public Sub CenterY As Float
    ' Vertical center used by the ball rendering.
    Return BreakoutMath.CenterOf(getY, getHeight)
End Sub

Public Sub SetPosition(aNewX As Float, aNewY As Float)
    ' Moves the entity without changing its size.
    setX(aNewX)
    setY(aNewY)
End Sub

Public Sub CollidesWithBox(aOtherLeft As Float, aOtherTop As Float, aOtherRight As Float, aOtherBottom As Float) As Boolean
    ' Rectangle collision helper. Safer than Intersects(GameEntity) after B4X++ flattening.
    Return BreakoutMath.Overlaps(Left, Top, Right, Bottom, aOtherLeft, aOtherTop, aOtherRight, aOtherBottom)
End Sub

' B4X++ visibility=protected
Private Sub EntityRect As B4XRect
    ' Reusable rectangle for B4XCanvas drawing.
    Dim entityArea As B4XRect
    entityArea.Initialize(Left, Top, Right, Bottom)
    Return entityArea
End Sub

' B4X++ modifiers=virtual
Public Sub B4XPP_Super_GameEntity_Render(aCvs As B4XCanvas)
    ' Default renderer for rectangular entities.
    If getVisible = False Then Return
    aCvs.DrawRect(EntityRect, getColor, True, 0)
End Sub


' B4X++ property: public X As Float default=0
Public Sub getX As Float
	Return B4XPP_Private_GameEntity_mX
End Sub

Public Sub setX(B4XPP_X As Float)
	B4XPP_Private_GameEntity_mX = B4XPP_X
End Sub

' B4X++ property: public Y As Float default=0
Public Sub getY As Float
	Return B4XPP_Private_GameEntity_mY
End Sub

Public Sub setY(B4XPP_Y As Float)
	B4XPP_Private_GameEntity_mY = B4XPP_Y
End Sub

' B4X++ property: public Width As Float default=10
Public Sub getWidth As Float
	Return B4XPP_Private_GameEntity_mWidth
End Sub

Public Sub setWidth(B4XPP_Width As Float)
	B4XPP_Private_GameEntity_mWidth = B4XPP_Width
End Sub

' B4X++ property: public Height As Float default=10
Public Sub getHeight As Float
	Return B4XPP_Private_GameEntity_mHeight
End Sub

Public Sub setHeight(B4XPP_Height As Float)
	B4XPP_Private_GameEntity_mHeight = B4XPP_Height
End Sub

' B4X++ property: public Color As Int default=0
Public Sub getColor As Int
	Return B4XPP_Private_GameEntity_mColor
End Sub

Public Sub setColor(B4XPP_Color As Int)
	B4XPP_Private_GameEntity_mColor = B4XPP_Color
End Sub

' B4X++ property: public Visible As Boolean default=True
Public Sub getVisible As Boolean
	Return B4XPP_Private_GameEntity_mVisible
End Sub

Public Sub setVisible(B4XPP_Visible As Boolean)
	B4XPP_Private_GameEntity_mVisible = B4XPP_Visible
End Sub



' B4X++ constructor: generated as Initialize
Public Sub Initialize(aX As Float, aY As Float, aWidth As Float, aHeight As Float, aColor As Int)
    ' Paddle is a specialized rectangle controlled by the mouse.
    B4XPP_Super_GameEntity_Initialize(aX, aY, aWidth, aHeight, aColor)
    setSpeed(720)
End Sub

Public Sub MoveCenter(aTargetCenterX As Float, aBoundsWidth As Float)
    ' Keeps the paddle centered under the mouse while staying inside the arena.
    Dim newLeft As Float = aTargetCenterX - getWidth / 2
    newLeft = BreakoutMath.ClampF(newLeft, 0, aBoundsWidth - getWidth)
    SetPosition(newLeft, getY)
End Sub

Public Sub Nudge(aDirection As Int, aDeltaSeconds As Float, aBoundsWidth As Float)
    ' Optional keyboard-style movement helper.
    MoveCenter(CenterX + aDirection * getSpeed * aDeltaSeconds, aBoundsWidth)
End Sub

' B4X++ modifiers=override
Public Sub Render(aCvs As B4XCanvas)
    ' Draws the paddle.
    If getVisible = False Then Return
    aCvs.DrawRect(EntityRect, getColor, True, 0)
End Sub


' B4X++ property: public Speed As Float default=720
Public Sub getSpeed As Float
	Return mSpeed
End Sub

Public Sub setSpeed(B4XPP_Speed As Float)
	mSpeed = B4XPP_Speed
End Sub
